### ISSUE TITLE
App crashed when notification comes after closing app.

### ISSUE THREAD

**Issue by hyurii** [tmt242001/Plugin.LocalNotification#10]
**Describe the bug**

**To Reproduce**
1. schedule notification for later , one minute for example
2. Build and run sample project
3.  Click notification send button
4. Close application
5. Wait for crash notification

**Expected behavior**
Notification comes like when application is opened

**Smartphone (please complete the following information):**
 - Device: s9
 - OS: Android 
 - Version API 28
- and diffrent simulators

**Additional context**
Logs:
Time	Device Name	Type	PID	Tag	Message
02-03 10:08:44.557	my_device	Debug	6758	Mono	Assembly Plugin.LocalNotification[0x9987f0a0] added to domain RootDomain, ref_count=1
02-03 10:08:47.503	my_device	Info	6001	Finsky	[303] com.google.android.finsky.bo.an.run(6): Stats for Executor: Db-notification_cache com.google.android.finsky.bo.ao@5f49da3[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
02-03 10:08:47.023	my_device	Debug	6758	Mono	Assembly Ref addref Plugin.LocalNotification[0x9987f0a0] -> System.Xml[0x97b1ad00]: 2
02-03 10:08:46.906	my_device	Debug	6758	Mono	Assembly Ref addref Plugin.LocalNotification[0x9987f0a0] -> Xamarin.Forms.Core[0x97b1a040]: 2
02-03 10:08:46.906	my_device	Debug	6758	Mono	Assembly Ref addref Plugin.LocalNotification[0x9987f0a0] -> mscorlib[0x9a57dfa0]: 46
02-03 10:08:46.830	my_device	Debug	6758	Mono	Assembly Ref addref Plugin.LocalNotification[0x9987f0a0] -> Mono.Android[0x97b1a400]: 43
02-03 10:08:44.563	my_device	Debug	6758	Mono	Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-x86-release/etc/mono/assemblies/Plugin.LocalNotification/Plugin.LocalNotification.config'.
02-03 10:08:44.563	my_device	Debug	6758	Mono	Config attempting to parse: '/storage/emulated/0/Android/data/com.GProjekt.XamarinTesterApp/files/.__override__/Plugin.LocalNotification.dll.config'.
02-03 10:08:44.563	my_device	Debug	6758	Mono	Assembly Loader loaded assembly from location: '/storage/emulated/0/Android/data/com.GProjekt.XamarinTesterApp/files/.__override__/Plugin.LocalNotification.dll'.
02-03 10:08:44.562	my_device	Debug	6758	Mono	AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-x86-release/lib/mono/aot-cache/x86/Plugin.LocalNotification.dll.so' not found: dlopen failed: library "/data/app/com.GProjekt.XamarinTesterApp-i_qpebq4DyTZx_5dnrqw7Q==/lib/x86/libaot-Plugin.LocalNotification.dll.so" not found
02-03 10:08:44.558	my_device	Debug	6758	Mono	AOT: image '/storage/emulated/0/Android/data/com.GProjekt.XamarinTesterApp/files/.__override__/Plugin.LocalNotification.dll.so' not found: dlopen failed: library "/data/app/com.GProjekt.XamarinTesterApp-i_qpebq4DyTZx_5dnrqw7Q==/lib/x86/libaot-Plugin.LocalNotification.dll.so" not found

Time	Device Name	Type	PID	Tag	Message
02-03 10:08:47.803	my_device	Info	6758	MonoDroid	System.InvalidOperationException: You MUST call Xamarin.Forms.Init(); prior to using it.
  at Xamarin.Forms.Device.get_PlatformServices () [0x00007] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Xamarin.Forms.Device.GetAssemblies () [0x00000] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Xamarin.Forms.DependencyService.Initialize () [0x00008] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x00000] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Plugin.LocalNotification.Platform.Droid.ScheduledNotificationJobService.OnStartJob (Android.App.Job.JobParameters jobParams) [0x00036] in <82eb727555a54d3e9c2630068744e9cd>:0 
  at Android.App.Job.JobService.n_OnStartJob_Landroid_app_job_JobParameters_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native__params) [0x00011] in <957bbfdfda4341e2939c881206c1140a>:0 
  at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)

Time	Device Name	Type	PID	Tag	Message
02-03 10:08:47.924	my_device	Error	6758	AndroidRuntime	android.runtime.JavaProxyThrowable: System.InvalidOperationException: You MUST call Xamarin.Forms.Init(); prior to using it.
  at Xamarin.Forms.Device.get_PlatformServices () [0x00007] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Xamarin.Forms.Device.GetAssemblies () [0x00000] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Xamarin.Forms.DependencyService.Initialize () [0x00008] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x00000] in <2ababf5361fa4e5a93abe01acecb2686>:0 
  at Plugin.LocalNotification.Platform.Droid.ScheduledNotificationJobService.OnStartJob (Android.App.Job.JobParameters jobParams) [0x00036] in <82eb727555a54d3e9c2630068744e9cd>:0 
  at Android.App.Job.JobService.n_OnStartJob_Landroid_app_job_JobParameters_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native__params) [0x00011] in <957bbfdfda4341e2939c881206c1140a>:0 
  at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)
	at plugin.localNotification.ScheduledNotificationJobService.n_onStartJob(Native Method)
	at plugin.localNotification.ScheduledNotificationJobService.onStartJob(ScheduledNotificationJobService.java:30)
	at android.app.job.JobService$1.onStartJob(JobService.java:71)
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by tmt242001** [comment]
fixed in v2.0.7
